version: '3'

services:
  db:
    image: postgres:16.0-alpine3.18
    container_name: testlo-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
